# usage: ./test.sh [version] example: ./test.sh 0.1
docker run \
   -e WORKSPACE_ID=$CHATBOT_WORKSPACE_ID_clone \
   -e CONVERSATION_USERNAME=$CHATBOT_CONVERSATION_USERNAME \
   -e CONVERSATION_PASSWORD=$CHATBOT_CONVERSATION_PASSWORD_clone \
   -e cloudant_username=$CLOUDANT_USER \
   -e cloudant_password=$CLOUDANT_PASSWORD \
   -e DB_MSG=$DB_MSG \
   -e SLACK_BOT_TOKEN=$SLACK_BOT_TOKEN \
   -e SLACK_BOT_USER=$SLACK_BOT_USER \
   -e DB_FEEDBACK=$DB_FEEDBACK \
   -e DB_IGC=$DB_IGC \
   -e DB_UNKNOWN=$DB_UNKNOWN \
   -e UNKNOWN_QUESTION_CHANNEL=$UNKNOWN_QUESTION_CHANNEL \
   -e INCOMMING_REQUEST_CHANNEL=$INCOMMING_REQUEST_CHANNEL \
   -e FEEDBACK_CHANNEL=$FEEDBACK_CHANNEL \
   -e ODM_DB_NAME=$ODM_DATABASE_PROD \
   -e ODM_USERID=$BOT_USER \
   -e ODM_USERID_PASSWORD=$BOT_PASSWORD \
   -e ODM_SCHEMA=$ODM_SCHEMA \
   -e ODM_HOST=$ODM_SERVER \
   -e ODM_PORT=$ODM_PORT_PROD \
   -p 8080:8080 \
   -it odmchatbot:$1 \
   npm start 
